---
name: Check pull requests (1.x branch)
on:
  pull_request:
    branches:
      - '1.x'

concurrency:
  group: "check-pull-request-1.x-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build with Java 8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: set up jdk 8
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Build with Maven
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: ./mvnw -s .build/maven-ci-settings.xml -B clean verify
  compatibility:
    runs-on: ubuntu-20.04
    name: Compatibility Check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Compatibility Check
        run: ./mvnw -s .build/maven-ci-settings.xml -pl '!bom' -B install revapi:check@check-compatibility -DskipTests -fae
